baseURL = "http://example.org/"
languageCode = "en-us"
theme = "timer-hugo"
title = "Timer | Responsive Multipurpose Bootstrap Hugo Template"
[[menu.main]]
name = "Contact"
url = "contact"
weight = 5
[[menu.main]]
name = "Blog"
url = "blog"
weight = 4
[[menu.main]]
name = "Gallery"
url = "gallery"
weight = 3
[[menu.main]]
name = "Service"
url = "service"
weight = 2
[[menu.main]]
name = "About"
url = "about"
weight = 1
[params]
author = "Themefisher"
contactFormAction = "#"
dateFormat = "6 January 2006"
description = "Airspace Hugo theme"
googleAnalitycsID = "Your ID"
home = "Home"
logo = "images/logo.png"
[params.about]
content = "Hello, I’m a UI/UX Designer & Front End Developer from Victoria, Australia. I hold a master degree of Web Design from the World University.And scrambled it to make a type specimen book. It has survived not only five centuries. <br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
enable = true
image = "images/about/about.jpg"
title = "ABOUT ME"
[params.banner]
bgImage = "images/slider.jpg"
btn = true
btnText = "Download More"
btnURL = "https://themefisher.com/"
description = "WITH 10 YEARS EXPERIENCE, I'VE OCCUPIED MANY ROLES INCLUDING DIGITAL DESIGN DIRECTOR, WEB DESIGNER AND DEVELOPER. THIS SITE SHOWCASES SOME OF MY WORK."
enable = true
heading = "HI, MY NAME IS JONATHON & I AM A"
[[params.banner.flipText]]
title = "DESIGNER"
[[params.banner.flipText]]
title = "DEVELOPER"
[[params.banner.flipText]]
title = "FATHER"
[params.cta]
btnText = "Contact with me"
btnURL = "/contact"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
enable = true
title = "SO WHAT YOU THINK ?"
[params.portfolio]
enable = true
subtitle = "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."
title = "Latest Works"
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"
[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"
[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
